# Dependencias
FROM node:23-alpine3.20 AS deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install


# Builder - Construye la aplicación
FROM node:23-alpine3.20 AS build

WORKDIR /usr/src/app

# Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el codigo fuente de la aplicación
COPY . .

RUN npx prisma generate

# RUN npm run test
RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force


# Crear la imagen final de Docker
FROM node:23-alpine3.20 AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# Copiar la carpeta de DIST
COPY --from=build /usr/src/app/dist ./dist

# Copiar el archivo de configuración de Prisma
COPY --from=build /usr/src/app/generated ./generated

ENV NODE_ENV=production

USER node

CMD [ "node", "dist/main.js" ]